# https://taskfile.dev

version: '3'

tasks:
  casa:
    alias: 
      - c
    cmds:
      - nixos-rebuild switch --flake '.#casa' |& nom
  wsl:
    alias: 
      - w
    cmds:
      - nixos-rebuild switch --flake .#wsl  |& nom
  up:
    cmds:
      - nix flake update |& nom
  fmt:
    cmds: 
      - nixpkgs-fmt . 
  zephyrus:
    alias: 
      - z
    cmds:
      - nixos-rebuild switch --flake .#zephyrus |& nom
 
