# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - sudo nixos-rebuild switch --flake .#wsl 
  up:
    cmds:
      - sudo nix flake update
  fmt:
    cmds: 
      - nixpkgs-fmt . 
