# https://taskfile.dev

version: '3'

tasks:
  aeternus:
    alias:
      - a
    cmds:
      - home-manager switch  --flake .#thebromo
  wsl:
    cmds:
      - sudo nixos-rebuild switch --flake .#wsl 
  up:
    cmds:
      - sudo nix flake update
  fmt:
    cmds: 
      - nixpkgs-fmt . 
  zephyrus:
    alias: 
      - z
    cmds:
      - sudo nixos-rebuild switch --flake .#zephyrus 
 
